### ISSUE TITLE
Health shouldn't be a constant

### ISSUE THREAD

**Issue by Madis0** [d4rkm0nkey/HorseStatsVanilla#7]
When riding a horse, the player can see the horse's health exactly. So why does this mod only show the maximum health on the inventory? Perhaps it could be shown like 12/15 if 12 is current and 15 is max.

**Comment by d4rkm0nkey** [comment]
Why would you need to see the health if you can also see the hearts?
The mod already displays the maximum health of the horse and the maximum health any horse can have, so there is no place for showing even more values and the health the horse has left is shown at the bottom.
The purpose of the mod is to make breeding easier, so I don't understand why you would want to have this extra information that you can already see at the healthbar.

**Comment by Madis0** [comment]
I thought it just looks a bit confusing:
* This entity's actual speed (speed range)
* This entity's actual jump height (jump height range)
* This entity's **maximum** health (maximum health range)

**Comment by d4rkm0nkey** [comment]
hmm I think here is some confusion.
It displays the entities maximum speed not the current speed.
It displays the entities maximum jump height.
It displays the entities maximum health.

I think what you want to say is that the displayed number is not the maximum health of the specific entity, but the maximum health any entity could potential get, which should not be the case.

Because as your title suggest, health is not constant over different horses. If it is on your client then it is a bug. If so, can you give details over the mods you have installed and provide screenshots that show, that the health is wrong?

**Comment by Madis0** [comment]
You're right, it was just my confusion.
